[package]
name = "gstreamer-rtsp-server"
version = "0.11.6"
authors = ["Mathieu Duponchelle <mathieu@centricular.com>", "Sebastian Dröge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer RTSP Server library"
repository = "https://github.com/sdroege/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://sdroege.github.io/rustdoc/gstreamer/gstreamer_rtsp_server"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"

[dependencies]
bitflags = "1.0"
libc = "0.2"
lazy_static = "1.0"
glib-sys = "0.6"
gio-sys = "0.6"
gobject-sys = "0.6"
gstreamer-sys = { version = "0.5", features = ["v1_8"] }
gstreamer-rtsp-sys = { version = "0.5", features = ["v1_8"] }
gstreamer-rtsp-server-sys = { version = "0.5", features = ["v1_8"] }
gstreamer-net-sys = { version = "0.5", features = ["v1_8"] }
glib = "0.5"
gio = "0.4"
gstreamer = { version = "0.11", path = "../gstreamer" }
gstreamer-rtsp = { version = "0.11", path = "../gstreamer-rtsp" }
gstreamer-net = { version = "0.11", path = "../gstreamer-net" }

[build-dependencies.rustdoc-stripper]
version = "0.1"
optional = true

[features]
v1_10 = ["gstreamer-sys/v1_10", "gstreamer-rtsp-sys/v1_10", "gstreamer-net-sys/v1_10", "gstreamer-rtsp-server-sys/v1_10"]
v1_12 = ["gstreamer-sys/v1_12", "gstreamer-rtsp-sys/v1_12", "gstreamer-net-sys/v1_12", "gstreamer-rtsp-server-sys/v1_12", "v1_10"]
v1_14 = ["gstreamer-sys/v1_14", "gstreamer-rtsp-sys/v1_14", "gstreamer-net-sys/v1_14", "gstreamer-rtsp-server-sys/v1_14", "v1_12"]
embed-lgpl-docs = ["rustdoc-stripper"]
purge-lgpl-docs = ["rustdoc-stripper"]
dox = ["gstreamer-rtsp-server-sys/dox", "glib/dox", "gstreamer/dox"]
default-features = []

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }
