[package]
authors = ["Russel Winder <russel@winder.org.uk>", "Sebastian Dröge <sebastian@centricular.com>"]
build = "build.rs"
documentation = "https://gstreamer.pages.freedesktop.org/gstreamer-rs/stable/latest/docs/gstreamer_mpegts_sys/"
description = "FFI bindings to libgstmpegts-1.0"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
license = "MIT"
name = "gstreamer-mpegts-sys"
readme = "README.md"

[package.version]
workspace = true

[package.categories]
workspace = true

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[package.metadata.system-deps.gstreamer_mpegts_1_0]
name = "gstreamer-mpegts-1.0"
version = "1.14"

[package.metadata.system-deps.gstreamer_mpegts_1_0.v1_16]
version = "1.16"

[package.metadata.system-deps.gstreamer_mpegts_1_0.v1_18]
version = "1.18"

[package.metadata.system-deps.gstreamer_mpegts_1_0.v1_20]
version = "1.20"

[package.metadata.system-deps.gstreamer_mpegts_1_0.v1_22]
version = "1.22"

[package.metadata.system-deps.gstreamer_mpegts_1_0.v1_24]
version = "1.23"

[lib]
name = "gstreamer_mpegts_sys"

[build-dependencies]
system-deps = "6"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.gstreamer-base-sys]
path = "../../gstreamer-base/sys"

[dependencies.gstreamer-sys]
path = "../../gstreamer/sys"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v1_16 = []
v1_18 = ["v1_16"]
v1_20 = ["v1_18"]
v1_22 = ["v1_20"]
v1_24 = ["v1_22"]
