dist: trusty
sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - liborc-0.4-dev
      - libglib2.0-dev
      - libxml2-dev
      - libgtk-3-dev

matrix:
  allow_failures:
    - rust: nightly

script:
    - rustc --version
    - cargo build --all
    - cargo test --all
    - cd examples && cargo build --features=gst-player

before_install:
- curl -L https://people.freedesktop.org/~slomo/gstreamer.tar.gz | tar xz
- export PKG_CONFIG_PATH=$PWD/gstreamer/lib/pkgconfig
- export GST_PLUGIN_SYSTEM_PATH=$PWD/gstreamer/lib/gstreamer-1.0
- export GST_PLUGIN_SCANNER=$PWD/gstreamer/libexec/gstreamer-1.0/gst-plugin-scanner
- export PATH=$PATH:$PWD/gstreamer/bin
- export RUSTFLAGS=-L$PWD/gstreamer/lib
- export LD_LIBRARY_PATH=$PWD/gstreamer/lib:$LD_LIBRARY_PATH
