[workspace]
resolver = "2"

default-members = [
  "gstreamer/sys",
  "gstreamer-app/sys",
  "gstreamer-audio/sys",
  "gstreamer-base/sys",
  "gstreamer-check/sys",
  "gstreamer-controller/sys",
  "gstreamer-editing-services/sys",
  "gstreamer-mpegts/sys",
  "gstreamer-net/sys",
  "gstreamer-pbutils/sys",
  "gstreamer-play/sys",
  "gstreamer-player/sys",
  "gstreamer-rtp/sys",
  "gstreamer-rtsp/sys",
  "gstreamer-rtsp-server/sys",
  "gstreamer-sdp/sys",
  "gstreamer-tag/sys",
  "gstreamer-video/sys",
  "gstreamer-webrtc/sys",
  "gstreamer",
  "gstreamer-app",
  "gstreamer-audio",
  "gstreamer-base",
  "gstreamer-check",
  "gstreamer-controller",
  "gstreamer-editing-services",
  "gstreamer-mpegts",
  "gstreamer-net",
  "gstreamer-pbutils",
  "gstreamer-play",
  "gstreamer-player",
  "gstreamer-rtp",
  "gstreamer-rtsp",
  "gstreamer-rtsp-server",
  "gstreamer-sdp",
  "gstreamer-tag",
  "gstreamer-validate",
  "gstreamer-video",
  "gstreamer-webrtc",
  "examples",
  "tutorials",
]

members = [
  "gstreamer/sys",
  "gstreamer-app/sys",
  "gstreamer-audio/sys",
  "gstreamer-base/sys",
  "gstreamer-check/sys",
  "gstreamer-controller/sys",
  "gstreamer-editing-services/sys",
  "gstreamer-gl/sys",
  "gstreamer-gl/egl/sys",
  "gstreamer-gl/wayland/sys",
  "gstreamer-gl/x11/sys",
  "gstreamer-mpegts/sys",
  "gstreamer-net/sys",
  "gstreamer-pbutils/sys",
  "gstreamer-play/sys",
  "gstreamer-player/sys",
  "gstreamer-rtp/sys",
  "gstreamer-rtsp/sys",
  "gstreamer-rtsp-server/sys",
  "gstreamer-sdp/sys",
  "gstreamer-tag/sys",
  "gstreamer-video/sys",
  "gstreamer-webrtc/sys",
  "gstreamer-allocators/sys",
  "gstreamer",
  "gstreamer-app",
  "gstreamer-audio",
  "gstreamer-base",
  "gstreamer-check",
  "gstreamer-controller",
  "gstreamer-editing-services",
  "gstreamer-gl",
  "gstreamer-gl/egl",
  "gstreamer-gl/wayland",
  "gstreamer-gl/x11",
  "gstreamer-mpegts",
  "gstreamer-net",
  "gstreamer-pbutils",
  "gstreamer-play",
  "gstreamer-player",
  "gstreamer-rtp",
  "gstreamer-rtsp",
  "gstreamer-rtsp-server",
  "gstreamer-sdp",
  "gstreamer-tag",
  "gstreamer-validate",
  "gstreamer-video",
  "gstreamer-webrtc",
  "gstreamer-allocators",
  "gstreamer-utils",
  "examples",
  "tutorials",
]

exclude = ["gir"]

[workspace.package]
version = "0.22.0"
categories = ["api-bindings", "multimedia"]
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
homepage = "https://gstreamer.freedesktop.org"
edition = "2021"
rust-version = "1.70"
