[workspace]
resolver = "2"

default-members = [
  "gstreamer/sys",
  "gstreamer-analytics/sys",
  "gstreamer-app/sys",
  "gstreamer-audio/sys",
  "gstreamer-base/sys",
  "gstreamer-check/sys",
  "gstreamer-controller/sys",
  "gstreamer-editing-services/sys",
  "gstreamer-mpegts/sys",
  "gstreamer-mse/sys",
  "gstreamer-net/sys",
  "gstreamer-pbutils/sys",
  "gstreamer-play/sys",
  "gstreamer-player/sys",
  "gstreamer-rtp/sys",
  "gstreamer-rtsp/sys",
  "gstreamer-rtsp-server/sys",
  "gstreamer-sdp/sys",
  "gstreamer-tag/sys",
  "gstreamer-video/sys",
  "gstreamer-webrtc/sys",
  "gstreamer",
  "gstreamer-analytics",
  "gstreamer-app",
  "gstreamer-audio",
  "gstreamer-base",
  "gstreamer-check",
  "gstreamer-controller",
  "gstreamer-editing-services",
  "gstreamer-mpegts",
  "gstreamer-mse",
  "gstreamer-net",
  "gstreamer-pbutils",
  "gstreamer-play",
  "gstreamer-player",
  "gstreamer-rtp",
  "gstreamer-rtsp",
  "gstreamer-rtsp-server",
  "gstreamer-sdp",
  "gstreamer-tag",
  "gstreamer-validate",
  "gstreamer-video",
  "gstreamer-webrtc",
  "examples",
  "tutorials",
]

members = [
  "gstreamer/sys",
  "gstreamer-analytics/sys",
  "gstreamer-app/sys",
  "gstreamer-audio/sys",
  "gstreamer-base/sys",
  "gstreamer-check/sys",
  "gstreamer-controller/sys",
  "gstreamer-d3d12/sys",
  "gstreamer-editing-services/sys",
  "gstreamer-gl/sys",
  "gstreamer-gl/egl/sys",
  "gstreamer-gl/wayland/sys",
  "gstreamer-gl/x11/sys",
  "gstreamer-mpegts/sys",
  "gstreamer-mse/sys",
  "gstreamer-net/sys",
  "gstreamer-pbutils/sys",
  "gstreamer-play/sys",
  "gstreamer-player/sys",
  "gstreamer-rtp/sys",
  "gstreamer-rtsp/sys",
  "gstreamer-rtsp-server/sys",
  "gstreamer-sdp/sys",
  "gstreamer-tag/sys",
  "gstreamer-video/sys",
  "gstreamer-webrtc/sys",
  "gstreamer-allocators/sys",
  "gstreamer",
  "gstreamer-analytics",
  "gstreamer-app",
  "gstreamer-audio",
  "gstreamer-base",
  "gstreamer-check",
  "gstreamer-controller",
  "gstreamer-d3d12",
  "gstreamer-editing-services",
  "gstreamer-gl",
  "gstreamer-gl/egl",
  "gstreamer-gl/wayland",
  "gstreamer-gl/x11",
  "gstreamer-mpegts",
  "gstreamer-mse",
  "gstreamer-net",
  "gstreamer-pbutils",
  "gstreamer-play",
  "gstreamer-player",
  "gstreamer-rtp",
  "gstreamer-rtsp",
  "gstreamer-rtsp-server",
  "gstreamer-sdp",
  "gstreamer-tag",
  "gstreamer-validate",
  "gstreamer-video",
  "gstreamer-webrtc",
  "gstreamer-allocators",
  "gstreamer-utils",
  "examples",
  "tutorials",
]

exclude = ["gir"]

[workspace.package]
version = "0.25.0"
categories = ["api-bindings", "multimedia"]
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
homepage = "https://gstreamer.freedesktop.org"
edition = "2021"
rust-version = "1.83"

[workspace.dependencies]
gio = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
gio-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
pangocairo = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "main" }
gstreamer-allocators-sys = { path = "gstreamer-allocators/sys" }
gstreamer-analytics-sys = { path = "gstreamer-analytics/sys" }
gstreamer-app-sys = {  path = "gstreamer-app/sys" }
gstreamer-audio-sys = { path = "./gstreamer-audio/sys"}
gstreamer-base-sys = { path = "./gstreamer-base/sys"}
gstreamer-check-sys = { path = "./gstreamer-check/sys" }
gstreamer-controller-sys = { path = "./gstreamer-controller/sys" }
gstreamer-d3d12-sys = { path = "./gstreamer-d3d12/sys" }
gstreamer-editing-services-sys = { path = "./gstreamer-editing-services/sys"}
gstreamer-gl-egl-sys = { path = "./gstreamer-gl/egl/sys"}
gstreamer-gl-wayland-sys = { path = "./gstreamer-gl/wayland/sys"}
gstreamer-gl-x11-sys = { path = "./gstreamer-gl/x11/sys"}
gstreamer-gl-sys = { path = "./gstreamer-gl/sys"}
gstreamer-mpegts-sys = { path = "./gstreamer-mpegts/sys"}
gstreamer-mse-sys = { path = "./gstreamer-mse/sys"}
gstreamer-net-sys = { path = "./gstreamer-net/sys"}
gstreamer-pbutils-sys = { path = "./gstreamer-pbutils/sys"}
gstreamer-play-sys = { path = "./gstreamer-play/sys" }
gstreamer-player-sys = { path = "./gstreamer-player/sys" }
gstreamer-rtp-sys = { path = "./gstreamer-rtp/sys" }
gstreamer-rtsp-sys = { path = "./gstreamer-rtsp/sys"}
gstreamer-rtsp-server-sys = { path = "./gstreamer-rtsp-server/sys" }
gstreamer-sdp-sys = { path = "./gstreamer-sdp/sys"}
gstreamer-tag-sys = { path = "./gstreamer-tag/sys" }
gstreamer-sys = { path = "./gstreamer/sys"}
gstreamer-validate-sys = { path = "./gstreamer-validate/sys" }
gstreamer-video-sys = { path = "./gstreamer-video/sys"}
gstreamer-webrtc-sys = { path = "./gstreamer-webrtc/sys" }
ges = { package = "gstreamer-editing-services", path = "./gstreamer-editing-services" }
gst = { package = "gstreamer", path = "./gstreamer" }
gst-allocators = { package = "gstreamer-allocators", path = "./gstreamer-allocators" }
gst-app = { package = "gstreamer-app", path = "./gstreamer-app" }
gst-audio = { package = "gstreamer-audio", path = "./gstreamer-audio" }
gst-base = { package = "gstreamer-base", path = "./gstreamer-base" }
gst-check = { package = "gstreamer-check", path = "./gstreamer-check" }
gst-d3d12 = { package = "gstreamer-d3d12", path = "./gstreamer-d3d12" }
gst-gl = { package = "gstreamer-gl", path = "./gstreamer-gl" }
gst-gl-egl = { package = "gstreamer-gl-egl", path = "./gstreamer-gl/egl" }
gst-gl-x11 = { package = "gstreamer-gl-x11", path = "./gstreamer-gl/x11" }
gst-net = { package = "gstreamer-net", path = "./gstreamer-net" }
gst-mse = { package = "gstreamer-mse", path = "./gstreamer-mse" }
gst-pbutils = { package = "gstreamer-pbutils", path = "./gstreamer-pbutils" }
gst-play = { package = "gstreamer-play", path = "./gstreamer-play" }
gst-player = { package = "gstreamer-player", path = "./gstreamer-player" }
gst-rtsp = { package = "gstreamer-rtsp", path = "./gstreamer-rtsp" }
gst-rtsp-server = { package = "gstreamer-rtsp-server", path = "./gstreamer-rtsp-server" }
gst-sdp = { package = "gstreamer-sdp", path = "./gstreamer-sdp" }
gst-video = { package = "gstreamer-video", path = "./gstreamer-video" }
