[workspace]
resolver = "2"

default-members = [
  "gstreamer/sys",
  "gstreamer-analytics/sys",
  "gstreamer-app/sys",
  "gstreamer-audio/sys",
  "gstreamer-base/sys",
  "gstreamer-check/sys",
  "gstreamer-controller/sys",
  "gstreamer-editing-services/sys",
  "gstreamer-mpegts/sys",
  "gstreamer-net/sys",
  "gstreamer-pbutils/sys",
  "gstreamer-play/sys",
  "gstreamer-player/sys",
  "gstreamer-rtp/sys",
  "gstreamer-rtsp/sys",
  "gstreamer-rtsp-server/sys",
  "gstreamer-sdp/sys",
  "gstreamer-tag/sys",
  "gstreamer-video/sys",
  "gstreamer-webrtc/sys",
  "gstreamer",
  "gstreamer-analytics",
  "gstreamer-app",
  "gstreamer-audio",
  "gstreamer-base",
  "gstreamer-check",
  "gstreamer-controller",
  "gstreamer-editing-services",
  "gstreamer-mpegts",
  "gstreamer-net",
  "gstreamer-pbutils",
  "gstreamer-play",
  "gstreamer-player",
  "gstreamer-rtp",
  "gstreamer-rtsp",
  "gstreamer-rtsp-server",
  "gstreamer-sdp",
  "gstreamer-tag",
  "gstreamer-validate",
  "gstreamer-video",
  "gstreamer-webrtc",
  "examples",
  "tutorials",
]

members = [
  "gstreamer/sys",
  "gstreamer-analytics/sys",
  "gstreamer-app/sys",
  "gstreamer-audio/sys",
  "gstreamer-base/sys",
  "gstreamer-check/sys",
  "gstreamer-controller/sys",
  "gstreamer-editing-services/sys",
  "gstreamer-gl/sys",
  "gstreamer-gl/egl/sys",
  "gstreamer-gl/wayland/sys",
  "gstreamer-gl/x11/sys",
  "gstreamer-mpegts/sys",
  "gstreamer-net/sys",
  "gstreamer-pbutils/sys",
  "gstreamer-play/sys",
  "gstreamer-player/sys",
  "gstreamer-rtp/sys",
  "gstreamer-rtsp/sys",
  "gstreamer-rtsp-server/sys",
  "gstreamer-sdp/sys",
  "gstreamer-tag/sys",
  "gstreamer-video/sys",
  "gstreamer-webrtc/sys",
  "gstreamer-allocators/sys",
  "gstreamer",
  "gstreamer-analytics",
  "gstreamer-app",
  "gstreamer-audio",
  "gstreamer-base",
  "gstreamer-check",
  "gstreamer-controller",
  "gstreamer-editing-services",
  "gstreamer-gl",
  "gstreamer-gl/egl",
  "gstreamer-gl/wayland",
  "gstreamer-gl/x11",
  "gstreamer-mpegts",
  "gstreamer-net",
  "gstreamer-pbutils",
  "gstreamer-play",
  "gstreamer-player",
  "gstreamer-rtp",
  "gstreamer-rtsp",
  "gstreamer-rtsp-server",
  "gstreamer-sdp",
  "gstreamer-tag",
  "gstreamer-validate",
  "gstreamer-video",
  "gstreamer-webrtc",
  "gstreamer-allocators",
  "gstreamer-utils",
  "examples",
  "tutorials",
]

exclude = ["gir"]

[workspace.package]
version = "0.22.2"
categories = ["api-bindings", "multimedia"]
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
homepage = "https://gstreamer.freedesktop.org"
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
gio = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
gio-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
pangocairo = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.19", version = "0.19" }
gstreamer-audio-sys = { path = "./gstreamer-audio/sys", version = "0.22" }
gstreamer-base-sys = { path = "./gstreamer-base/sys", version = "0.22" }
gstreamer-gl-sys = { path = "./gstreamer-gl/sys", version = "0.22" }
gstreamer-net-sys = { path = "./gstreamer-net/sys", version = "0.22" }
gstreamer-pbutils-sys = { path = "./gstreamer-pbutils/sys", version = "0.22" }
gstreamer-rtsp-sys = { path = "./gstreamer-rtsp/sys", version = "0.22" }
gstreamer-sdp-sys = { path = "./gstreamer-sdp/sys", version = "0.22" }
gstreamer-sys = { path = "./gstreamer/sys", version = "0.22" }
gstreamer-video-sys = { path = "./gstreamer-video/sys", version = "0.22" }
ges = { package = "gstreamer-editing-services", path = "./gstreamer-editing-services", version = "0.22" }
gst = { package = "gstreamer", path = "./gstreamer", version = "0.22" }
gst-allocators = { package = "gstreamer-allocators", path = "./gstreamer-allocators", version = "0.22" }
gst-app = { package = "gstreamer-app", path = "./gstreamer-app", version = "0.22" }
gst-audio = { package = "gstreamer-audio", path = "./gstreamer-audio", version = "0.22" }
gst-base = { package = "gstreamer-base", path = "./gstreamer-base", version = "0.22" }
gst-check = { package = "gstreamer-check", path = "./gstreamer-check", version = "0.22" }
gst-gl = { package = "gstreamer-gl", path = "./gstreamer-gl", version = "0.22" }
gst-gl-egl = { package = "gstreamer-gl-egl", path = "./gstreamer-gl/egl", version = "0.22" }
gst-gl-x11 = { package = "gstreamer-gl-x11", path = "./gstreamer-gl/x11", version = "0.22" }
gst-net = { package = "gstreamer-net", path = "./gstreamer-net", version = "0.22" }
gst-pbutils = { package = "gstreamer-pbutils", path = "./gstreamer-pbutils", version = "0.22" }
gst-play = { package = "gstreamer-play", path = "./gstreamer-play", version = "0.22" }
gst-player = { package = "gstreamer-player", path = "./gstreamer-player", version = "0.22" }
gst-rtsp = { package = "gstreamer-rtsp", path = "./gstreamer-rtsp", version = "0.22" }
gst-rtsp-server = { package = "gstreamer-rtsp-server", path = "./gstreamer-rtsp-server", version = "0.22" }
gst-sdp = { package = "gstreamer-sdp", path = "./gstreamer-sdp", version = "0.22" }
gst-video = { package = "gstreamer-video", path = "./gstreamer-video", version = "0.22" }
