[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
]
deny = [
  "GPL-1.0",
  "GPL-2.0",
  "GPL-3.0",
  "AGPL-1.0",
  "AGPL-3.0",
]
copyleft = "deny"
allow-osi-fsf-free = "either"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"

# Various cocoa crates are in the middle of updating to newer versions
[[bans.skip]]
name = "foreign-types"
version = "0.3"
[[bans.skip]]
name = "foreign-types-shared"
version = "0.1"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
  "https://github.com/gtk-rs/gtk-rs-core",
]

# Various crates depend on an older version of syn
[[bans.skip]]
name = "syn"
version = "1.0"
