[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
]
deny = [
  "GPL-1.0",
  "GPL-2.0",
  "GPL-3.0",
  "AGPL-1.0",
  "AGPL-3.0",
]
copyleft = "deny"
allow-osi-fsf-free = "either"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
skip-tree = [
  # Winit introduces quite a few duplicate (outdated!) dependencies together
  # with its direct dependant glutin.
  { name = "winit", version = "0.24" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
  "https://github.com/gtk-rs/gtk-rs",
  "https://github.com/gtk-rs/gtk-rs-core",
]
