[options]
girs_dir = "gir-files"
library = "GstVideo"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-video"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
single_version_file = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
    "GstBase",
]

generate = [
    "GstVideo.VideoFormat",
    "GstVideo.VideoFormatFlags",
    "GstVideo.VideoTileMode",
    "GstVideo.VideoInterlaceMode",
    "GstVideo.VideoFlags",
    "GstVideo.VideoChromaSite",
    "GstVideo.VideoColorMatrix",
    "GstVideo.VideoTransferFunction",
    "GstVideo.VideoColorPrimaries",
    "GstVideo.VideoMultiviewMode",
    "GstVideo.VideoMultiviewFlags",
    "GstVideo.VideoFieldOrder",
    "GstVideo.VideoFrameFlags",
    "GstVideo.VideoMultiviewFramePacking",
    "GstVideo.VideoFilter",
]

manual = [
    "GObject.Object",
    "Gst.Object",
    "Gst.Element",
    "GstBase.BaseTransform",
    "GstVideo.VideoInfo",
    "GstVideo.VideoFormatInfo",
    "GstVideo.VideoColorimetry",
    "GstVideo.VideoColorRange",
    "GstVideo.VideoFrame",
]

[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"

[[object]]
name = "GstVideo.VideoOverlay"
status = "generate"

    [[object.function]]
    name = "set_render_rectangle"
        [object.function.return]
        bool_return_is_error = "Failed to set render rectangle"
