[options]
girs_dir = "gir-files"
library = "GstGL"
version = "1.0"
min_cfg_version = "1.14"
target_path = "gstreamer-gl-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
gstreamer-base="GstBase"
gstreamer-video="GstVideo"

[[object]]
name = "GstGL.GLDisplayEGL"
status = "generate"
cfg_condition = "feature = \"egl\""
    [[object.function]]
    pattern = ".*"
    cfg_condition = "feature = \"egl\""

[[object]]
name = "GstGL.GLDisplayEGLClass"
status = "generate"
cfg_condition = "feature = \"egl\""

[[object]]
name = "GstGL.GL_DISPLAY_EGL_NAME"
status = "generate"
cfg_condition = "feature = \"egl\""
    [[object.constant]]
    pattern = ".*"
    cfg_condition = "feature = \"egl\""
