[options]
girs_dir = "gir-files"
library = "GstApp"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-app-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
]

[external_libraries]
gstreamer="Gst"
gstreamer_base="GstBase"
