[options]
girs_dir = "gir-files"
library = "GstSdp"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-sdp"
work_mode = "normal"
concurrency = "send"
generate_safety_asserts = true
single_version_file = true
doc_target_path = "docs/gstreamer-sdp/docs.md"
generate_display_trait = false

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
    "GstSdp.MIKEYCacheType",
    "GstSdp.MIKEYEncAlg",
    "GstSdp.MIKEYKVType",
    "GstSdp.MIKEYKeyDataType",
    "GstSdp.MIKEYMacAlg",
    "GstSdp.MIKEYMapType",
    "GstSdp.MIKEYPRFFunc",
    "GstSdp.MIKEYPayloadType",
    "GstSdp.MIKEYSecProto",
    "GstSdp.MIKEYSecSRTP",
    "GstSdp.MIKEYTSType",
    "GstSdp.MIKEYType",
]

manual = [
    "GLib.Bytes",
]

[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"

[[object]]
name = "GstSdp.MIKEYMessage"
status = "generate"
    [[object.function]]
    name = "add_cs_srtp"
       [object.function.return]
       bool_return_is_error = "Failed to add the Crypto policy for SRTP"

    [[object.function]]
    name = "add_pke"
       [object.function.return]
       bool_return_is_error = "Failed to add the PKE payload"

    [[object.function]]
    name = "add_rand"
       [object.function.return]
       bool_return_is_error = "Failed to add the RAND payload"

    [[object.function]]
    name = "add_rand_len"
       [object.function.return]
       bool_return_is_error = "Failed to add the RAND payload with random bytes"

    [[object.function]]
    name = "add_t"
       [object.function.return]
       bool_return_is_error = "Failed to add the T payload"

    [[object.function]]
    name = "add_t_now_ntp_utc"
       [object.function.return]
       bool_return_is_error = "Failed to add the T payload with current time"

    [[object.function]]
    name = "remove_cs_srtp"
       [object.function.return]
       bool_return_is_error = "Failed to remove the SRTP policy"

    [[object.function]]
    name = "remove_payload"
       [object.function.return]
       bool_return_is_error = "Failed to remove the payload"

    [[object.function]]
    name = "set_info"
       [object.function.return]
       bool_return_is_error = "Failed to set the information"

    [[object.function]]
    name = "to_caps"
       [object.function.return]
       bool_return_is_error = "Failed to fill caps with SRTP parameters"

    [[object.function]]
    name = "replace_payload"
    ignore = true

    [[object.function]]
    name = "insert_payload"
    ignore = true

    [[object.function]]
    name = "add_payload"
    ignore = true

    [[object.function]]
    name = "get_payload"
    ignore = true

    [[object.function]]
    name = "base64_encode"
    ignore = true

[[object]]
name = "GstSdp.MIKEYPayload"
status = "generate"
    [[object.function]]
    name = "kemac_add_sub"
    ignore = true

    [[object.function]]
    name = "kemac_remove_sub"
       [object.function.return]
       bool_return_is_error = "Failed to remove the sub payload"

    [[object.function]]
    name = "kemac_get_sub"
    ignore = true

    [[object.function]]
    name = "kemac_set"
       [object.function.return]
       bool_return_is_error = "Failed to set the KEMAC parameters"

    [[object.function]]
    name = "key_data_set_interval"
    ignore = true

    [[object.function]]
    name = "key_data_set_key"
       [object.function.return]
       bool_return_is_error = "Failed to set the key"

    [[object.function]]
    name = "key_data_set_salt"
       [object.function.return]
       bool_return_is_error = "Failed to set the salt key data"

    [[object.function]]
    name = "key_data_set_spi"
       [object.function.return]
       bool_return_is_error = "Failed to set the SPI/MKI validity"

    [[object.function]]
    name = "pke_set"
       [object.function.return]
       bool_return_is_error = "Failed to set the PKE values"

    [[object.function]]
    name = "rand_set"
       [object.function.return]
       bool_return_is_error = "Failed to set the random values"

    [[object.function]]
    name = "sp_add_param"
       [object.function.return]
       bool_return_is_error = "Failed to add the parameter"

    [[object.function]]
    name = "sp_remove_param"
       [object.function.return]
       bool_return_is_error = "Failed to remove the parameter"

    [[object.function]]
    name = "sp_set"
       [object.function.return]
       bool_return_is_error = "Failed to set the Security Policy parameters"

    [[object.function]]
    name = "t_set"
    ignore = true