[options]
girs_dir = "gir-files"
library = "Gst"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer"
work_mode = "normal"
concurrency = "send+sync"

external_libraries = [
    "GLib",
    "GObject",
]

generate = [
    "Gst.ClockTime",
    "Gst.Pipeline",
    "Gst.State",
    "Gst.StateChangeReturn",
    "Gst.StateChange",
    "Gst.SeekFlags",
    "Gst.SeekType",
    "Gst.FlowReturn",
    "Gst.PadDirection",
    "Gst.PadTemplate",
    "Gst.URIHandler",
    "Gst.URIType",
    "Gst.ElementFactoryListType",
    "Gst.Format",
    "Gst.BufferingMode",
    "Gst.CoreError",
    "Gst.ResourceError",
    "Gst.LibraryError",
    "Gst.StreamError",
    "Gst.PluginError",
    "Gst.ParseError",
    "Gst.URIError",
    "Gst.StructureChangeType",
    "Gst.StreamStatusType",
    "Gst.DeviceMonitor",
    "Gst.DeviceProvider",
    "Gst.DeviceProviderFactory",
    "Gst.Stream",
    "Gst.StreamCollection",
    "Gst.StreamType",
    "Gst.StreamFlags",
    "Gst.PadLinkReturn",
    "Gst.ProgressType",
]

manual = [
    "GLib.Error",
    "Gst.Message",
    "Gst.Structure",
]

[[object]]
name = "Gst.Bin"
status = "generate"
    [[object.function]]
    name = "add"
        [object.function.return]
        bool_return_is_error = "Failed to add element"

    [[object.function]]
    name = "remove"
        [object.function.return]
        bool_return_is_error = "Failed to remove element"

    [[object.function]]
    name = "recalculate_latency"
        [object.function.return]
        bool_return_is_error = "Failed to recalculate latency"

    [[object.function]]
    name = "sync_children_states"
        [object.function.return]
        bool_return_is_error = "Failed to sync children states"

[[object]]
name = "Gst.Bus"
status = "generate"
trait = false
    [[object.function]]
    name = "remove_watch"
    # Needs manual bindings and GSource support in glib-rs
    ignore = true

    [[object.function]]
    name = "timed_pop_filtered"
    # Uses enum as flags
    ignore = true
    [[object.function]]
    name = "pop_filtered"
    # Uses enum as flags
    ignore = true
    [[object.function]]
    name = "poll"
    # Uses enum as flags
    ignore = true

[[object]]
name = "Gst.Clock"
status = "generate"
    [[object.function]]
    name = "set_master"
        [object.function.return]
        bool_return_is_error = "Failed to set master clock"

    [[object.function]]
    name = "wait_for_sync"
        [object.function.return]
        bool_return_is_error = "Timed out waiting for sync"

[[object]]
name = "Gst.Element"
status = "generate"
    [[object.function]]
    name = "add_pad"
        [object.function.return]
        bool_return_is_error = "Failed to add pad"

    [[object.function]]
    name = "remove_pad"
        [object.function.return]
        bool_return_is_error = "Failed to remove pad"

    [[object.function]]
    name = "link"
        [object.function.return]
        bool_return_is_error = "Failed to link elements"

    [[object.function]]
    name = "link_pads"
        [object.function.return]
        bool_return_is_error = "Failed to link pads"

    [[object.function]]
    name = "seek"
        [object.function.return]
        bool_return_is_error = "Failed to seek"

    [[object.function]]
    name = "seek_simple"
        [object.function.return]
        bool_return_is_error = "Failed to seek"

    [[object.function]]
    name = "set_clock"
        [object.function.return]
        bool_return_is_error = "Failed to set clock"

    [[object.function]]
    name = "sync_state_with_parent"
        [object.function.return]
        bool_return_is_error = "Failed to sync state with parent"

[[object]]
name = "Gst.ElementFactory"
status = "generate"
trait = false

[[object]]
name = "Gst.Device"
status = "generate"
    [[object.function]]
    name = "get_properties"
    # Structure is not a GObject
    ignore = true

    [[object.property]]
    name = "properties"
    # Structure is not a GObject
    ignore = true


[[object]]
name = "Gst.Object"
status = "generate"
    [[object.function]]
    name = "set_name"
        [object.function.return]
        bool_return_is_error = "Failed to set object name"

    [[object.function]]
    name = "get_name"
        [object.function.return]
        nullable = false

    [[object.function]]
    name = "get_path_string"
        [object.function.return]
        nullable = false

    [[object.function]]
    name = "set_parent"
        [object.function.return]
        bool_return_is_error = "Failed to set parent object"

    [[object.function]]
    name = "sync_values"
        [object.function.return]
        bool_return_is_error = "Failed to sync values"

[[object]]
name = "Gst.Pad"
status = "generate"
    [[object.function]]
    name = "link_maybe_ghosting"
        [object.function.return]
        bool_return_is_error = "Failed to link pad, possibly ghosting"

    [[object.function]]
    name = "unlink"
        [object.function.return]
        bool_return_is_error = "Failed to unlink pad"

    [[object.function]]
    name = "pause_task"
        [object.function.return]
        bool_return_is_error = "Failed to pause pad task"

    [[object.function]]
    name = "stop_task"
        [object.function.return]
        bool_return_is_error = "Failed to stop pad task"

    [[object.function]]
    name = "set_active"
        [object.function.return]
        bool_return_is_error = "Failed to activate pad"

[[object]]
name = "Gst.Plugin"
status = "generate"
trait = false

[[object]]
name = "Gst.*"
status = "generate"
    [[object.function]]
    name = "update_registry"
        [object.function.return]
        bool_return_is_error = "Failed to update registry"

    [[object.function]]
    name = "util_dump_mem"
    ignore = true

    [[object.function]]
    name = "protection_select_system"
    # unsupported array type
    ignore = true

