[options]
girs_dir = "gir-files"
library = "Gst"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-sys"
work_mode = "sys"

ignore = [
    "Gst.VERSION_MAJOR",
    "Gst.VERSION_MINOR",
    "Gst.VERSION_MICRO",
    "Gst.VERSION_NANO",
    "Gst.ERROR_SYSTEM",
    "Gst.TIME_FORMAT",
    "Gst.STIME_FORMAT",
    "Gst.PTR_FORMAT",
    "Gst.SEGMENT_FORMAT",
    "Gst.FOURCC_FORMAT",
]

external_libraries = [
    "GLib",
    "GObject",
]
