[options]
girs_dir = "gir-files"
library = "GstBase"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-base-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
    "1.8",
    "1.6",
    "1.4",
    "1.2",
]

external_libraries = [
    "GLib",
    "GObject",
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17"

[external_libraries]
gstreamer="Gst"

[[object]]
name = "GstBase.AggregatorStartTimeSelection"
status = "generate"
version = "1.18"

[[object]]
name = "GstBase.Adapter"
status = "generate"
    [[object.function]]
    name = "distance_from_discont"
    version = "1.10"

[[object]]
name = "GstBase.BaseParseFrame"
status = "generate"
    [[object.function]]
    name = "copy"
    version = "1.12.1"
