[options]
girs_dir = "gir-files"
library = "GES"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-editing-services-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
    "1.8",
    "1.6",
    "1.4",
    "1.2",
]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17"

[external_libraries]
gstreamer="Gst"
gstreamer_base="GstBase"
gstreamer_pbutils="GstPbutils"

[[object]]
name = "GES.Clip"
status = "generate"
    [[object.function]]
    name = "add_child_to_track"
    version = "1.18"
    [[object.function]]
    name = "get_timeline_time_from_internal_time"
    version = "1.18"

[[object]]
name = "GES.ClipAsset"
status = "generate"
    [[object.function]]
    name = "get_frame_time"
    version = "1.18"
    [[object.function]]
    name = "get_natural_framerate"
    version = "1.18"

[[object]]
name = "GES.Layer"
status = "generate"
    [[object.function]]
    name = "get_active_for_track"
    version = "1.18"
    [[object.function]]
    name = "set_active_for_tracks"
    version = "1.18"

[[object]]
name = "GES.Marker"
status = "generate"
version = "1.18"

[[object]]
name = "GES.SourceClipAsset"
status = "generate"
version = "1.18"

[[object]]
name = "GES.Timeline"
status = "generate"
    [[object.function]]
    name = "get_frame_at"
    version = "1.18"
    [[object.function]]
    name = "get_frame_time"
    version = "1.18"

[[object]]
name = "GES.TrackElement"
status = "generate"
    [[object.function]]
    name = "has_internal_source"
    version = "1.18"
    [[object.function]]
    name = "set_has_internal_source"
    version = "1.18"

[[object]]
name = "GES.TrackElementAsset"
status = "generate"
    [[object.function]]
    name = "get_natural_framerate"
    version = "1.18"

[[object]]
name = "GES.UriSourceAsset"
status = "generate"
    [[object.function]]
    name = "is_image"
    version = "1.18"

[[object]]
name = "GES.VideoSource"
status = "generate"
    [[object.function]]
    name = "get_natural_size"
    version = "1.18"

[[object]]
name = "GES.MetaContainer"
status = "generate"
    [[object.function]]
    name = "register_static_meta"
    version = "1.18"
