[options]
girs_dir = "gir-files"
library = "GES"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-editing-services"
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
generate_display_trait = false

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "Gst",
    "GstPbutils",
]

manual = [
    "GLib.Error",
    "GLib.Source",
    "GLib.DateTime",
    "Gio.Cancellable",
    "Gio.AsyncReadyCallback",
    "GObject.Object",
    "Gst.Segment",
    "Gst.StaticCaps",
    "Gst.StaticPadTemplate",
    "GstPbutils.EncodingProfile",
    "GstPbutils.DiscovererInfo",
    "GstPbutils.DiscovererStreamInfo",
    "Gst.Object",
    "Gst.Element",
    "Gst.Pad",
    "Gst.Pipeline",
]

generate = [
    "GES.EditMode",
    "GES.PipelineFlags",
    "GES.Edge",
    "GES.Effect",
    "GES.TrackType",
    "GES.BaseEffect",
    "GES.TimelineElement",
    "GES.Group",
    "GES.TrackElement",
    "GES.Layer",
    "GES.Clip",
    "GES.UriClip",
    "GES.Asset",
    "GES.UriClipAsset",
    "GES.UriSourceAsset",
    "GES.Extractable",
    "GES.Project",
]

[[object]]
name = "Gst.Structure"
status = "manual"
ref_mode = "ref-mut"

[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.Buffer"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.BufferList"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.Sample"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.ClockTime"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "GES.Timeline"
status = "generate"
    [[object.function]]
    name = "append_layer"
        [object.function.return]
        nullable = false

    [[object.function]]
    name = "load_from_uri"
        [object.function.return]
        bool_return_is_error = "Failed to load from uri"

    [[object.function]]
    name = "add_layer"
        [object.function.return]
        bool_return_is_error = "Failed to add layer"

    [[object.function]]
    name = "remove_layer"
        [object.function.return]
        bool_return_is_error = "Failed to remove layer"

    [[object.function]]
    name = "add_track"
        [object.function.return]
        bool_return_is_error = "Failed to add track"

    [[object.function]]
    name = "move_layer"
        [object.function.return]
        bool_return_is_error = "Failed to move layer"


[[object]]
name = "GES.Container"
status = "generate"
trait_name = "GESContainerExt"
    [[object.function]]
    name = "add"
        [object.function.return]
        bool_return_is_error = "Failed to add element"

    [[object.function]]
    name = "remove"
        [object.function.return]
        bool_return_is_error = "Failed to remove element"

    [[object.function]]
    name = "edit"
        [object.function.return]
        bool_return_is_error = "Failed to edit container"

[[object]]
name = "GES.Pipeline"
status = "generate"
trait_name = "GESPipelineExt"
    [[object.function]]
    name = "set_render_settings"
        [object.function.return]
        bool_return_is_error = "Failed to set render settings"

    [[object.function]]
    name = "set_mode"
        [object.function.return]
        bool_return_is_error = "Failed to set mode"

    [[object.function]]
    name = "save_thumbnail"
        [object.function.return]
        bool_return_is_error = "Failed to save thumbnail"

[[object]]
name = "GES.Track"
status = "generate"
trait_name = "GESTrackExt"
    [[object.function]]
    name = "add_element"
        [object.function.return]
        bool_return_is_error = "Failed to add element"

    [[object.function]]
    name = "remove_element"
        [object.function.return]
        bool_return_is_error = "Failed to remove element"
