[options]
girs_dir = "gir-files"
library = "Gst"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
    "1.8",
    "1.6",
    "1.4",
    "1.2",
]

external_libraries = [
    "GLib",
    "GObject",
]

ignore = [
    "Gst.VERSION_MAJOR",
    "Gst.VERSION_MINOR",
    "Gst.VERSION_MICRO",
    "Gst.VERSION_NANO",
    "Gst.ERROR_SYSTEM",
    "Gst.TIME_FORMAT",
    "Gst.STIME_FORMAT",
    "Gst.PTR_FORMAT",
    "Gst.SEGMENT_FORMAT",
    "Gst.FOURCC_FORMAT",
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17"
