[package]
name = "gstreamer-editing-services"
version = "0.12.2"
authors = ["Thibault Saunier <tsaunier@igalia.com>", "Sebastian Dröge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer Editing Services"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://slomo.pages.freedesktop.org/rustdocs/gstreamer/gstreamer_editing_services"
keywords = ["gstreamer", "multimedia", "gnome", "nle", "video editing"]
build = "build.rs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glib-sys = "0.7"
gio-sys = "0.7"
gobject-sys = "0.7"
gstreamer-sys = { version = "0.6", features = ["v1_8"] }
gstreamer-base-sys = { version = "0.6", features = ["v1_8"] }
gstreamer-pbutils-sys = { version = "0.6", features = ["v1_8"] }
gstreamer-editing-services-sys = { version = "0.6", features = ["v1_8"] }
glib = "0.6"
gio = "0.5"
gstreamer = { version = "0.12", path = "../gstreamer" }
gstreamer-base = { version = "0.12", path = "../gstreamer-base" }
gstreamer-pbutils = { version = "0.12", path = "../gstreamer-pbutils" }

[build-dependencies.rustdoc-stripper]
version = "0.1"
optional = true

[features]
v1_8 = ["gstreamer-editing-services-sys/v1_8"]
v1_10 = ["gstreamer-editing-services-sys/v1_10"]
v1_12 = ["gstreamer-editing-services-sys/v1_12", "v1_10"]
v1_14 = ["gstreamer-editing-services-sys/v1_14", "v1_12"]
v1_16 = ["gstreamer-editing-services-sys/v1_16", "v1_14"]
embed-lgpl-docs = ["rustdoc-stripper"]
purge-lgpl-docs = ["rustdoc-stripper"]
dox = ["gstreamer-editing-services-sys/dox", "glib/dox", "gstreamer/dox"]
