[options]
girs_directories = ["../gir-files", "../gst-gir-files"]
library = "GstSdp"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "normal"
concurrency = "send"
generate_safety_asserts = true
single_version_file = true
generate_display_trait = false
trust_return_value_nullability = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
]

manual = [
    "GLib.Bytes",
]

[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"
