[package]
name = "gstreamer"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
bitflags = "0.9"
libc = "0.2"
glib-sys = { version = "0.3.4", git = "https://github.com/gtk-rs/sys" }
gobject-sys = { version = "0.3.4", git = "https://github.com/gtk-rs/sys" }
gstreamer-sys = { version = "0.1.1", git = "https://github.com/sdroege/gstreamer-sys", features = ["v1_8"] }
glib = { version = "0.1.3", git = "https://github.com/gtk-rs/glib" }

[features]
v1_10 = ["gstreamer-sys/v1_10", "v1_8"]
v1_12 = ["gstreamer-sys/v1_12", "v1_10"]
v1_8 = ["gstreamer-sys/v1_8"]

