[package]
name = "gstreamer"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
bitflags = "0.8"
libc = "0.2"
glib-sys = "0.3.4"
gobject-sys = "0.3.4"
gstreamer-sys = "0.1.1"
glib = "0.1.3"
