[build-dependencies]
system-deps = "1.3"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.gstreamer-base-sys]
path = "../gstreamer-base-sys"
features = ["v1_14"]

[dependencies.gstreamer-sys]
path = "../gstreamer-sys"
features = ["v1_14"]

[dependencies.gstreamer-video-sys]
path = "../gstreamer-video-sys"
features = ["v1_14"]

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
dox = []
egl = []
x11 = []
wayland = []
v1_16 = []
v1_18 = ["v1_16"]

[lib]
name = "gstreamer_gl_sys"

[package]
authors = ["Sebastian Dröge <sebastian@centricular.com>", "Víctor Manuel Jáquez Leal <vjaquez@igalia.com>"]
build = "build.rs"
description = "FFI bindings to libgstgl-1.0"
documentation = "https://slomo.pages.freedesktop.org/rustdocs/gstreamer-sys/gstreamer_gl_sys/"
homepage = "https://gstreamer.freedesktop.org"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
license = "MIT"
links = "gstgl-1.0"
name = "gstreamer-gl-sys"
readme = "README.md"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs-sys"
version = "0.10.0"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.gstreamer_gl_1_0]
name = "gstreamer-gl-1.0"
version = "1.14"

[package.metadata.system-deps.gstreamer_gl_1_0.feature-versions]
v1_16 = "1.16"
v1_18 = "1.18"
