[package]
name = "tutorials"
version = "0.15.0"
license = "MIT"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
gdk = { git = "https://github.com/gtk-rs/gdk", optional = true }
gtk = { git = "https://github.com/gtk-rs/gtk", optional = true }
gstreamer = { path = "../gstreamer" }
gstreamer-audio = { path = "../gstreamer-audio" }
gstreamer-video = { path = "../gstreamer-video" }
gstreamer-app = { path = "../gstreamer-app" }
gstreamer-pbutils = { path = "../gstreamer-pbutils" }
byte-slice-cast = "0.3"
failure = "0.1.0"

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
