[package]
name = "tutorials"
version = "0.12.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
gdk = { git = "https://github.com/gtk-rs/gdk", optional = true }
gtk = { git = "https://github.com/gtk-rs/gtk", features = ["v3_10"], optional = true }
gstreamer = { path = "../gstreamer" }
gstreamer-audio = { path = "../gstreamer-audio" }
gstreamer-video = { path = "../gstreamer-video" }
gstreamer-app = { path = "../gstreamer-app" }
gstreamer-pbutils = { path = "../gstreamer-pbutils" }
byte-slice-cast = "0.2"
failure = "0.1.0"
# Newer versions do not compile with rustc 1.28 so pin it for the time being
# This dependency comes from backtrace, which comes from failure
rustc-demangle = "0.1.10"

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
