[package]
name = "tutorials"
version = "0.16.0"
license = "MIT"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = "0.10"
gdk = { version = "0.13", optional = true }
gtk = { version = "0.9", optional = true }
gstreamer = { version = "0.16", path = "../gstreamer" }
gstreamer-audio = { version = "0.16", path = "../gstreamer-audio" }
gstreamer-video = { version = "0.16", path = "../gstreamer-video" }
gstreamer-app = { version = "0.16", path = "../gstreamer-app" }
gstreamer-pbutils = { version = "0.16", path = "../gstreamer-pbutils" }
byte-slice-cast = "0.3"
failure = "0.1.0"

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
