[package]
name = "tutorials"
version = "0.12.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = "0.6"
gdk = { version = "0.9", optional = true }
gtk = { version = "0.5", features = ["v3_10"], optional = true }
gstreamer = { version = "0.12", path = "../gstreamer" }
gstreamer-audio = { version = "0.12", path = "../gstreamer-audio" }
gstreamer-video = { version = "0.12", path = "../gstreamer-video" }
gstreamer-app = { version = "0.12", path = "../gstreamer-app" }
byte-slice-cast = "0.2"

[badges]
gitlab = { repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", branch = "master" }

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
