[package]
name = "tutorials"
version = "0.10.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = "0.4"
gdk = { version = "0.7", optional = true }
gtk = { version = "0.3", features = ["v3_10"], optional = true }
gstreamer = { version = "0.10", path = "../gstreamer" }
gstreamer-audio = { version = "0.10", path = "../gstreamer-audio" }
gstreamer-video = { version = "0.10", path = "../gstreamer-video" }
gstreamer-app = { version = "0.10", path = "../gstreamer-app" }
send-cell = "0.1"
byte-slice-cast = "0.1"

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
