[package]
name = "tutorials"
version = "0.17.0"
license = "MIT"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2018"

[dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs" }
gdk = { git = "https://github.com/gtk-rs/gtk-rs", optional = true }
gtk = { git = "https://github.com/gtk-rs/gtk-rs", optional = true }
gst = { package = "gstreamer", path = "../gstreamer" }
gst-audio = { package = "gstreamer-audio", path = "../gstreamer-audio" }
gst-video = { package = "gstreamer-video", path = "../gstreamer-video", optional = true }
gst-app = { package = "gstreamer-app", path = "../gstreamer-app" }
gst-pbutils = { package = "gstreamer-pbutils", path = "../gstreamer-pbutils" }
byte-slice-cast = "1"
anyhow = "1"

[features]
tutorial5 = ["gtk", "gdk", "gst-video"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
