[package]
name = "tutorials"
version = "0.17.1"
license = "MIT"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2018"

[dependencies]
glib = { version = "0.14" }
gdk = { version = "0.14", optional = true }
gtk = { version = "0.14", optional = true }
gst = { package = "gstreamer", version = "0.17", path = "../gstreamer" }
gst-audio = { package = "gstreamer-audio", version = "0.17", path = "../gstreamer-audio" }
gst-video = { package = "gstreamer-video", version = "0.17", path = "../gstreamer-video", optional = true }
gst-app = { package = "gstreamer-app", version = "0.17", path = "../gstreamer-app" }
gst-pbutils = { package = "gstreamer-pbutils", version = "0.17", path = "../gstreamer-pbutils" }
byte-slice-cast = "1"
anyhow = "1"
termion = { version = "1.5", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"

[features]
tutorial5 = ["gtk", "gdk", "gst-video"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]

[[bin]]
name = "basic-tutorial-13"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-1"
required-features = ["termion"]
