[package]
name = "tutorials"
version = "0.12.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = { version = "0.7" }
gdk = { version = "0.10", optional = true }
gtk = { version = "0.6", optional = true }
gstreamer = { version = "0.13", path = "../gstreamer" }
gstreamer-audio = { version = "0.13", path = "../gstreamer-audio" }
gstreamer-video = { version = "0.13", path = "../gstreamer-video" }
gstreamer-app = { version = "0.13", path = "../gstreamer-app" }
gstreamer-pbutils = { version = "0.13", path = "../gstreamer-pbutils" }
byte-slice-cast = "0.2"
failure = "0.1.0"

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
