[package]
name = "tutorials"
version = "0.14.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = { version = "0.8" }
gdk = { version = "0.11", optional = true }
gtk = { version = "0.7", optional = true }
gstreamer = { version = "0.14", path = "../gstreamer" }
gstreamer-audio = { version = "0.14", path = "../gstreamer-audio" }
gstreamer-video = { version = "0.14", path = "../gstreamer-video" }
gstreamer-app = { version = "0.14", path = "../gstreamer-app" }
gstreamer-pbutils = { version = "0.14", path = "../gstreamer-pbutils" }
byte-slice-cast = "0.3"
failure = "0.1.0"

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
