[package]
name = "tutorials"
version = "0.20.3"
license = "MIT"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2021"
rust-version = "1.64"

[dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.17", version = "0.17" }
gdk = { git = "https://github.com/gtk-rs/gtk3-rs", branch = "0.17", version = "0.17.0", optional = true }
gtk = { git = "https://github.com/gtk-rs/gtk3-rs", branch = "0.17", version = "0.17.0", optional = true }
gst = { package = "gstreamer", path = "../gstreamer", version = "0.20" }
gst-audio = { package = "gstreamer-audio", path = "../gstreamer-audio", version = "0.20" }
gst-video = { package = "gstreamer-video", path = "../gstreamer-video", version = "0.20", optional = true }
gst-app = { package = "gstreamer-app", path = "../gstreamer-app", version = "0.20" }
gst-pbutils = { package = "gstreamer-pbutils", path = "../gstreamer-pbutils", version = "0.20" }
byte-slice-cast = "1"
anyhow = "1"
termion = { version = "2", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
objc = "0.2.7"

[features]
tutorial5 = ["gtk", "gdk", "gst-video"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]

[[bin]]
name = "basic-tutorial-13"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-1"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-2"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-5"
required-features = ["termion", "gst-video"]
