[package]
name = "tutorials"
version = "0.21.1"
license = "MIT"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2021"
rust-version = "1.70"

[dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.18", version = "0.18" }
gst = { package = "gstreamer", path = "../gstreamer", version = "0.21" }
gst-audio = { package = "gstreamer-audio", path = "../gstreamer-audio", version = "0.21" }
gst-video = { package = "gstreamer-video", path = "../gstreamer-video", version = "0.21", optional = true }
gst-app = { package = "gstreamer-app", path = "../gstreamer-app", version = "0.21" }
gst-pbutils = { package = "gstreamer-pbutils", path = "../gstreamer-pbutils", version = "0.21" }
byte-slice-cast = "1"
anyhow = "1"
termion = { version = "2", optional = true }
async-channel = "2.0.0"
futures = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2.7"

[[bin]]
name = "basic-tutorial-13"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-1"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-2"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-5"
required-features = ["termion", "gst-video"]
