[build-dependencies]
system-deps = "7"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
workspace = true

[dependencies.gobject-sys]
workspace = true

[dependencies.gstreamer-sys]
workspace = true

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v1_14_1 = []
v1_14_3 = ["v1_14_1"]
v1_16 = ["v1_14_3"]
v1_18 = ["v1_16"]
v1_20 = ["v1_18"]
v1_22 = ["v1_20"]
v1_24 = ["v1_22"]
v1_26 = ["v1_24"]
v1_28 = ["v1_26"]

[lib]
name = "gstreamer_base_sys"

[package]
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
build = "build.rs"
description = "FFI bindings to libgstbase-1.0"
documentation = "https://gstreamer.freedesktop.org/documentation/rust/stable/latest/docs/gstreamer_base_sys/"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
license = "MIT"
name = "gstreamer-base-sys"
readme = "README.md"

[package.version]
workspace = true

[package.categories]
workspace = true

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[package.metadata.system-deps.gstreamer_base_1_0]
name = "gstreamer-base-1.0"
version = "1.14"

[package.metadata.system-deps.gstreamer_base_1_0.v1_14_1]
version = "1.14.1"

[package.metadata.system-deps.gstreamer_base_1_0.v1_14_3]
version = "1.14.3"

[package.metadata.system-deps.gstreamer_base_1_0.v1_16]
version = "1.16"

[package.metadata.system-deps.gstreamer_base_1_0.v1_18]
version = "1.18"

[package.metadata.system-deps.gstreamer_base_1_0.v1_20]
version = "1.20"

[package.metadata.system-deps.gstreamer_base_1_0.v1_22]
version = "1.22"

[package.metadata.system-deps.gstreamer_base_1_0.v1_24]
version = "1.24"

[package.metadata.system-deps.gstreamer_base_1_0.v1_26]
version = "1.26"

[package.metadata.system-deps.gstreamer_base_1_0.v1_28]
version = "1.27"
