[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GES"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.24",
    "1.22",
    "1.20",
    "1.18",
    "1.16",
]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]

ignore = [
    "GES.VERSION_MAJOR",
    "GES.VERSION_MINOR",
    "GES.VERSION_MICRO",
    "GES.VERSION_NANO",
]

[external_libraries]
gstreamer="Gst"
gstreamer_pbutils="GstPbutils"

[[object]]
name = "GES.*"
status = "generate"
    [[object.function]]
    name = "frame_composition_meta_api_get_type"
    version = "1.24"

[[object]]
name = "GES.PitiviFormatter"
# Deprecated since GStreamer 1.0 & causes ABI test failures
# See: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/1425#note_2380648
status = "ignore"
    [[object.function]]
    pattern = ".+"
    ignore = true

[[object]]
name = "GES.PitiviFormatterClass"
# Deprecated since GStreamer 1.0 & causes ABI test failures
# See: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/1425#note_2380648
status = "ignore"
