[options]
girs_dir = "../../gir-files"
library = "GstGL"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
]

ignore = [
    "GstGL.GL_COLOR_CONVERT_VIDEO_CAPS",
    "GstGL.GL_COLOR_CONVERT_FORMATS",
    "GstGL.GL_MEMORY_VIDEO_FORMATS_STR",
]

external_libraries = [
    "GLib",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
gstreamer-base="GstBase"
gstreamer-video="GstVideo"

#[[object]]
#name = "GstGL.GL_COLOR_CONVERT_VIDEO_CAPS"
#status = "manual"
