[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstGL"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.22",
    "1.20",
    "1.18",
    "1.16",
]

ignore = [
    "GstGL.GL_COLOR_CONVERT_VIDEO_CAPS",
    "GstGL.GL_COLOR_CONVERT_FORMATS",
    "GstGL.GL_MEMORY_VIDEO_FORMATS_STR",
]

external_libraries = [
    "GLib",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
gstreamer-base="GstBase"
gstreamer-video="GstVideo"

#[[object]]
#name = "GstGL.GL_COLOR_CONVERT_VIDEO_CAPS"
#status = "manual"

[[object]]
name = "GstGL.GLBuffer"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.20"

[[object]]
name = "GstGL.GLMemory"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.20"

[[object]]
name = "GstGL.GLMemoryPBO"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.20"

[[object]]
name = "GstGL.GLRenderbuffer"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.20"
