[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstPlay"
version = "1.0"
min_cfg_version = "1.20"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.24",
    "1.22"
]

external_libraries = [
    "GLib",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
gstreamer_video="GstVideo"
