[package]
name = "examples"
version = "0.11.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = "0.5"
gstreamer = { version = "0.11", path = "../gstreamer" }
gstreamer-app = { version = "0.11", path = "../gstreamer-app" }
gstreamer-audio = { version = "0.11", path = "../gstreamer-audio" }
gstreamer-video = { version = "0.11", path = "../gstreamer-video" }
gstreamer-pbutils = { version = "0.11", path = "../gstreamer-pbutils" }
gstreamer-player = { version = "0.11", path = "../gstreamer-player", optional = true }
gstreamer-rtsp = { version = "0.11", path = "../gstreamer-rtsp", optional = true }
gstreamer-rtsp-server = { version = "0.11", path = "../gstreamer-rtsp-server", optional = true }
gstreamer-rtsp-server-sys = { version = "0.5", features = ["v1_8"] }
gtk = { version = "0.4", features = ["v3_6"], optional = true }
gdk = { version = "0.8", optional = true }
gio = { version = "0.4", optional = true }
futures = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
send-cell = "0.1"
byte-slice-cast = "0.1"
failure = "0.1"
failure_derive = "0.1"

[features]
gst-player = ["gstreamer-player"]
gtksink = ["gtk", "gio"]
gtkvideooverlay = ["gtk", "gdk", "gio"]
gtkvideooverlay-x11 = ["gtkvideooverlay"]
gtkvideooverlay-quartz = ["gtkvideooverlay"]
tokio = ["gstreamer/futures", "futures", "tokio-core"]
gst-rtsp-server = ["gstreamer-rtsp-server"]
gst-rtsp-server-record = ["gstreamer-rtsp-server", "gstreamer-rtsp", "gio"]
default-features = []
v1_10 = ["gstreamer/v1_10"]

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }

[[bin]]
name = "appsink"

[[bin]]
name = "appsrc"

[[bin]]
name = "decodebin"

[[bin]]
name = "events"

[[bin]]
name = "gtksink"
required-features = ["gtksink"]

[[bin]]
name = "gtkvideooverlay"
required-features = ["gtkvideooverlay"]

[[bin]]
name = "iterator"

[[bin]]
name = "launch_glib_main"

[[bin]]
name = "launch"

[[bin]]
name = "pad_probes"

[[bin]]
name = "playbin"

[[bin]]
name = "player"
required-features = ["gst-player"]

[[bin]]
name = "queries"

[[bin]]
name = "rtpfecclient"

[[bin]]
name = "rtpfecserver"

[[bin]]
name = "rtsp-server"
required-features = ["gst-rtsp-server"]

[[bin]]
name = "tagsetter"

[[bin]]
name = "toc"

[[bin]]
name = "tokio"
required-features = ["tokio"]

[[bin]]
name = "rtsp-server-record"
required-features = ["gst-rtsp-server-record"]

[[bin]]
name = "discoverer"
