[package]
name = "examples"
version = "0.10.1"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = "0.4"
gstreamer = { version = "0.10", path = "../gstreamer" }
gstreamer-app = { version = "0.10", path = "../gstreamer-app" }
gstreamer-audio = { version = "0.10", path = "../gstreamer-audio" }
gstreamer-video = { version = "0.10", path = "../gstreamer-video" }
gstreamer-player = { version = "0.10", path = "../gstreamer-player", optional = true }
gtk = { version = "0.3", features = ["v3_6"], optional = true }
gdk = { version = "0.7", optional = true }
gio = { version = "0.3", optional = true }
futures = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
send-cell = "0.1"
byte-slice-cast = "0.1"
failure = "0.1"
failure_derive = "0.1"

[features]
gst-player = ["gstreamer-player"]
gtksink = ["gtk", "gio"]
gtkvideooverlay = ["gtk", "gdk", "gio"]
gtkvideooverlay-x11 = ["gtkvideooverlay"]
gtkvideooverlay-quartz = ["gtkvideooverlay"]
tokio = ["gstreamer/futures", "futures", "tokio-core"]
default-features = []
v1_10 = ["gstreamer/v1_10"]

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }
