[options]
girs_directories = ["../gir-files", "../gst-gir-files"]
library = "GstCheck"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
single_version_file = true
generate_display_trait = false
trust_return_value_nullability = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
]

manual = [
    "GLib.Bytes",
    "GObject.Object",
    "GObject.Value",
    "Gst.AllocationParams",
    "Gst.Allocator",
    "Gst.Bin",
    "Gst.Buffer",
    "Gst.BufferPool",
    "Gst.Caps",
    "Gst.ClockID",
    "Gst.ClockTimeDiff",
    "Gst.ClockType",
    "Gst.Element",
    "Gst.ElementFactory",
    "Gst.ElementFlags",
    "Gst.Event",
    "Gst.EventType",
    "Gst.FlowReturn",
    "Gst.Harness",
    "Gst.Object",
    "Gst.Pad",
    "Gst.PadProbeType",
    "Gst.Segment",
    "Gst.State",
    "Gst.StaticPadTemplate",
    "Gst.SystemClock",
]

[[object]]
name = "Gst.Clock"
status = "manual"
    # id_ functions are wrongly listed on Clock in .gir,
    # but should be associated to the `GstClockID` alias.
    [[object.function]]
    pattern = "id_.*"
    ignore = true

[[object]]
name = "Gst.ClockTime"
status = "manual"
conversion_type = "Option"

[[object]]
name = "GstCheck.Harness"
status = "manual"

    [[object.function]]
    name = "new_with_element"
    rename = "with_element"

    [[object.function]]
    name = "new_with_padnames"
    rename = "with_padnames"

[[object]]
name = "GstCheck.TestClock"
status = "generate"
final_type = true
    [[object.function]]
    name = "get_next_entry_time"
        [object.function.return]
        mandatory = true

    [[object.function]]
    name = "new_with_start_time"
        [[object.function.parameter]]
        name = "start_time"
        mandatory = true

    [[object.function]]
    name = "set_time"
        [[object.function.parameter]]
        name = "new_time"
        mandatory = true

    [[object.function]]
    name = "has_id"
    manual = true
    [[object.function]]
    name = "peek_next_pending_id"
    manual = true
    [[object.function]]
    name = "process_id"
    manual = true
    [[object.function]]
    name = "process_id_list"
    manual = true
    [[object.function]]
    name = "process_next_clock_id"
    manual = true
    [[object.function]]
    name = "wait_for_multiple_pending_ids"
    manual = true
    [[object.function]]
    name = "wait_for_next_pending_id"
    manual = true
    [[object.function]]
    name = "timed_wait_for_multiple_pending_ids"
    manual = true
