[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstRtp"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.22",
    "1.20",
    "1.18",
    "1.16",
]

external_libraries = [
    "GLib",
]

[external_libraries]
gstreamer="Gst"
gstreamer_base="GstBase"

[[object]]
name = "GstRtp.*"
status = "generate"
    [[object.function]]
    name = "rtp_source_meta_api_get_type"
    version = "1.16"
