[options]
girs_directories = ["../../../gir-files", "../../../gst-gir-files"]
library = "GstVulkanXCB"
min_cfg_version = "1.18"
version = "1.0"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.24",
    "1.22",
    "1.20",
]

external_libraries = [
    "GLib",
]

generate = [
    "GstVulkanXCB.VulkanDisplayXCB",
]

[external_libraries]
gstreamer-vulkan = "GstVulkan"
