[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstWebRTC"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.26",
    "1.24",
    "1.22",
    "1.20",
    "1.18",
    "1.16",
]

external_libraries = [
    "GLib",
]

[external_libraries]
gstreamer = "Gst"
gstreamer_sdp = "GstSdp"

[[object]]
name = "GstWebRTC.WebRTCSCTPTransport"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.20"
