[package]
name = "gstreamer-validate"
authors = ["Philippe Normand <philn@igalia.com>"]
description = "Rust bindings for GStreamer Validate library"
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://gstreamer.freedesktop.org/documentation/rust/stable/latest/docs/gstreamer_validate/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
version.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true 
edition.workspace = true 
rust-version.workspace = true 

[dependencies]
libc = "0.2"
gstreamer-validate-sys.workspace = true
glib.workspace = true
gst = { workspace = true, features = ["v1_22"] }

[dev-dependencies]
gir-format-check = "0.1"
tempfile = "3"

[features]
default = []
v1_24 = ["gst/v1_24", "gstreamer-validate-sys/v1_24"]
v1_26 = ["gst/v1_26", "gstreamer-validate-sys/v1_26", "v1_24"]
v1_28 = ["gst/v1_28", "gstreamer-validate-sys/v1_28", "v1_26"]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
