[package]
name = "gstreamer-player"
version = "0.8.1"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer Player library"
repository = "https://github.com/sdroege/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://sdroege.github.io/rustdoc/gstreamer/gstreamer-player"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"

[dependencies]
bitflags = "0.9"
libc = "0.2"
glib-sys = "0.4"
gobject-sys = "0.4"
gstreamer-player-sys = { version = "0.2", features = ["v1_12"] }
glib = "0.3"
gstreamer = { version = "0.8", path = "../gstreamer", features = ["v1_12"] }

[build-dependencies.rustdoc-stripper]
version = "0.1"
optional = true

[features]
embed-lgpl-docs = ["rustdoc-stripper"]
purge-lgpl-docs = ["rustdoc-stripper"]
default-features = []

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }
