[package]
name = "gstreamer-player"
version = "0.17.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer Player library"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://gstreamer.pages.freedesktop.org/gstreamer-rs/gstreamer_player/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"
edition = "2018"

[dependencies]
bitflags = "1.0"
libc = "0.2"
ffi = { package = "gstreamer-player-sys", path = "../gstreamer-player/sys" }
glib = { git = "https://github.com/gtk-rs/gtk-rs" }
gst = { package = "gstreamer", path = "../gstreamer", features = ["v1_12"] }
gst-video = { package = "gstreamer-video", path = "../gstreamer-video", features = ["v1_12"] }

[build-dependencies]
gstreamer-rs-lgpl-docs = { path = "../docs", optional = true }

[features]
default = []
v1_14 = ["gst/v1_14", "gst-video/v1_14", "ffi/v1_14"]
v1_16 = ["gst/v1_16", "gst-video/v1_16", "ffi/v1_16", "v1_14"]
v1_18 = ["gst/v1_18", "gst-video/v1_18", "ffi/v1_18", "v1_16"]
embed-lgpl-docs = ["gstreamer-rs-lgpl-docs"]
purge-lgpl-docs = ["gstreamer-rs-lgpl-docs"]

[package.metadata.docs.rs]
features = ["embed-lgpl-docs"]
