[options]
girs_directories = ["../../../gir-files", "../../../gst-gir-files"]
library = "GstGLEGL"
min_cfg_version = "1.14"
version = "1.0"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.20",
    "1.18",
    "1.16",
]

external_libraries = [
    "GLib",
]

generate = [
    "GstGLEGL.GLDisplayEGL",
]

[external_libraries]
gstreamer-gl = "GstGL"
