[package]
name = "gstreamer-webrtc"
version = "0.17.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer WebRTC library"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://gstreamer.pages.freedesktop.org/gstreamer-rs/gstreamer_webrtc/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"
edition = "2018"

[dependencies]
libc = "0.2"
ffi = { package = "gstreamer-webrtc-sys", path = "../gstreamer-webrtc/sys" }
glib = { git = "https://github.com/gtk-rs/gtk-rs" }
gst = { package = "gstreamer", path = "../gstreamer", features = ["v1_14"] }
gst-sdp = { package = "gstreamer-sdp", path = "../gstreamer-sdp", features = ["v1_14"] }

[build-dependencies]
gstreamer-rs-lgpl-docs = { path = "../docs", optional = true }

[features]
default = []
embed-lgpl-docs = ["gstreamer-rs-lgpl-docs"]
purge-lgpl-docs = ["gstreamer-rs-lgpl-docs"]
dox = ["v1_18", "ffi/dox", "glib/dox", "gst/dox", "gst-sdp/dox"]
v1_16 = ["gst/v1_16", "gst-sdp/v1_16", "ffi/v1_16"]
v1_18 = ["gst/v1_18", "gst-sdp/v1_18", "ffi/v1_18", "v1_16"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]
