[package]
name = "gstreamer-webrtc"
version = "0.12.1"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer WebRTC library"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://slomo.pages.freedesktop.org/rustdocs/gstreamer/gstreamer_webrtc"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"

[dependencies]
libc = "0.2"
glib-sys = "0.7"
gobject-sys = "0.7"
gstreamer-sys = "0.6"
gstreamer-webrtc-sys = "0.6"
glib = "0.6"
gstreamer = { version = "0.12", path = "../gstreamer", features = ["v1_14"] }
gstreamer-sdp = { version = "0.12", path = "../gstreamer-sdp" }

[build-dependencies.rustdoc-stripper]
version = "0.1"
optional = true

[features]
embed-lgpl-docs = ["rustdoc-stripper"]
purge-lgpl-docs = ["rustdoc-stripper"]
dox = ["gstreamer-webrtc-sys/dox", "glib/dox", "gstreamer/dox"]
default-features = []

[badges]
gitlab = { repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", branch = "master" }
