[package]
name = "gstreamer-webrtc"
version = "0.14.3"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer WebRTC library"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://slomo.pages.freedesktop.org/rustdocs/gstreamer/gstreamer_webrtc"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"

[dependencies]
libc = "0.2"
glib-sys = { version = "0.9" }
gobject-sys = { version = "0.9" }
gstreamer-sys = { version = "0.8" }
gstreamer-webrtc-sys = { version = "0.8" }
glib = { version = "0.8" }
gstreamer = { version = "0.14", path = "../gstreamer", features = ["v1_14"] }
gstreamer-sdp = { version = "0.14", path = "../gstreamer-sdp" }

[build-dependencies.rustdoc-stripper]
version = "0.1"
optional = true

[features]
default = []
embed-lgpl-docs = ["rustdoc-stripper"]
purge-lgpl-docs = ["rustdoc-stripper"]
dox = ["gstreamer-webrtc-sys/dox", "glib/dox", "gstreamer/dox"]
v1_16 = ["gstreamer-sys/v1_16", "gstreamer-webrtc-sys/v1_16"]
