[options]
girs_dir = "../gir-files"
library = "GstWebRTC"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
single_version_file = true
generate_display_trait = false

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
    "GstSdp",
]

generate = [
    "GstWebRTC.WebRTCDTLSTransportState",
    "GstWebRTC.WebRTCICEGatheringState",
    "GstWebRTC.WebRTCICEConnectionState",
    "GstWebRTC.WebRTCICERole",
    "GstWebRTC.WebRTCICEComponent",
    "GstWebRTC.WebRTCDTLSSetup",
    "GstWebRTC.WebRTCPeerConnectionState",
    "GstWebRTC.WebRTCRTPTransceiverDirection",
    "GstWebRTC.WebRTCSignalingState",
    "GstWebRTC.WebRTCStatsType",
    "GstWebRTC.WebRTCBundlePolicy",
    "GstWebRTC.WebRTCDataChannelState",
    "GstWebRTC.WebRTCICETransportPolicy",
    "GstWebRTC.WebRTCPriorityType",
    "GstWebRTC.WebRTCSCTPTransportState",
    "GstWebRTC.WebRTCFECType",
]

manual = [
    "GLib.Bytes",
    "GLib.Error",
    "GObject.Object",
    "Gst.Structure",
    "GstSdp.SDPMessage",
]

[[object]]
name = "GstWebRTC.WebRTCDTLSTransport"
status = "generate"
final_type = true

[[object]]
name = "GstWebRTC.WebRTCICETransport"
status = "generate"
final_type = true

[[object]]
name = "GstWebRTC.WebRTCRTPReceiver"
status = "generate"
final_type = true

[[object]]
name = "GstWebRTC.WebRTCRTPSender"
status = "generate"
final_type = true

[[object]]
name = "GstWebRTC.WebRTCRTPTransceiver"
status = "generate"
final_type = true

[[object]]
name = "GstWebRTC.WebRTCSessionDescription"
status = "generate"
final_type = true

    [[object.function]]
    name = "new"
    # takes ownership of SDP message
    ignore = true

[[object]]
name = "GstWebRTC.WebRTCDataChannel"
status = "generate"
final_type = true

    [[object.function]]
    name = "on_error"
    # takes ownership of SDP message
    manual = true

[[object]]
name = "GstWebRTC.WebRTCSDPType"
status = "generate"

    [[object.function]]
    name = "to_string"
        [object.function.return]
        nullable = false
