[package]
name = "gstreamer-gl-x11"
authors = [
    "Sebastian Dröge <sebastian@centricular.com>",
    "Víctor M. Jáquez L. <vjaquez@igalia.com>"
]
description = "Rust bindings for GStreamer GL library (X11 support)"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://gstreamer.freedesktop.org/documentation/rust/stable/latest/docs/gstreamer_gl_x11/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
version.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true 
edition.workspace = true 
rust-version.workspace = true 

[dependencies]
libc = "0.2"
gstreamer-gl-x11-sys.workspace = true
glib.workspace = true
gst.workspace = true
gst-gl.workspace = true

[dev-dependencies]
gir-format-check = "0.1"

[features]
default = []
v1_16 = ["gst/v1_16", "gst-gl/v1_16", "gstreamer-gl-x11-sys/v1_16"]
v1_18 = ["gst/v1_18", "gst-gl/v1_18", "gstreamer-gl-x11-sys/v1_18", "v1_16"]
v1_20 = ["gst/v1_20", "gst-gl/v1_20", "gstreamer-gl-x11-sys/v1_20", "v1_18"]
v1_22 = ["gst/v1_22", "gst-gl/v1_22", "gstreamer-gl-x11-sys/v1_22", "v1_20"]
v1_24 = ["gst/v1_24", "gst-gl/v1_24", "gstreamer-gl-x11-sys/v1_24", "v1_22"]
v1_26 = ["gst/v1_26", "gst-gl/v1_26", "gstreamer-gl-x11-sys/v1_26", "v1_24"]
v1_28 = ["gst/v1_28", "gst-gl/v1_28", "gstreamer-gl-x11-sys/v1_28", "v1_26"]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
