[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstVulkan"
version = "1.0"
min_cfg_version = "1.18"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.24",
    "1.22",
    "1.20",
]

ignore = [
]

external_libraries = [
    "GLib",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
gstreamer-base="GstBase"
gstreamer-video="GstVideo"

[[object]]
name = "GstVulkan.VulkanBufferMemory"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.18"

[[object]]
name = "GstVulkan.VulkanImageMemory"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.18"
