[package]
name = "gstreamer-gl"
version = "0.15.7"
authors = ["Sebastian Dröge <sebastian@centricular.com>",
           "Víctor M. Jáquez L. <vjaquez@igalia.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer GL library"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://slomo.pages.freedesktop.org/rustdocs/gstreamer/gstreamer_gl"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"

[dependencies]
bitflags = "1.0"
byteorder = "1"
libc = "0.2"
lazy_static = "1.0"
glib-sys = { version = "0.9" }
gobject-sys = { version = "0.9" }
gstreamer-sys = { version = "0.8", features = ["v1_14"] }
gstreamer-video-sys = { version = "0.8", features = ["v1_14"] }
gstreamer-gl-sys = { version = "0.8" }
glib = { version = "0.9" }
gstreamer = { version = "0.15", path = "../gstreamer", features = ["v1_14"] }
gstreamer-base = { version = "0.15", path = "../gstreamer-base", features = ["v1_14"] }
gstreamer-video = { version = "0.15", path = "../gstreamer-video", features = ["v1_14"] }

[build-dependencies]
rustdoc-stripper = { version = "0.1", optional = true }

[features]
default = []
dox = ["v1_16", "gstreamer-gl-sys/dox", "glib/dox", "gstreamer/dox", "gstreamer-base/dox"]
egl = ["gstreamer-gl-sys/egl"]
x11 = ["gstreamer-gl-sys/x11"]
wayland = ["gstreamer-gl-sys/wayland"]
embed-lgpl-docs = ["rustdoc-stripper"]
purge-lgpl-docs = ["rustdoc-stripper"]
v1_16 = ["gstreamer/v1_16", "gstreamer-base/v1_16", "gstreamer-video/v1_16", "gstreamer-gl-sys/v1_16"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]
